### ISSUE TITLE
Why is the range of the quantitative values rdfs:Class?

### ISSUE THREAD

**Issue by alanruttenberg** [OpenHPS/POSO#1]
I'm referring to pitch, roll, yaw, x-axis, y-axis, z-axis.

**Comment by Maximvdw** [comment]
It seems to be a mistake that slipped in. This should be `owl:Thing`. To clarify; POSO does not force the unit/ontology that you use to represent the numerical value of pitch/roll/... so you can specify that "you have a pitch of 10 degrees" using qudt or the OM ontology.

Thanks for reporting! Will fix it this week.
